language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
before_script:
  - 'npm install -g bower grunt-cli karma codecov'
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    package:
     - g++-4.8
cache:
  directories:
   - node_modules
script: 
   - npm test
   - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
   - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
