language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
before_script:
  - 'npm install -g bower grunt-cli karma'
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    package:
     - g++-4.8
cache:
  directories:
   - node_modules
script: npm test
